// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package grpc.employeeService;

public interface AddEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeService.AddEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 employeeNumber = 1;</code>
   */
  int getEmployeeNumber();

  /**
   * <code>string employeeName = 2;</code>
   */
  java.lang.String getEmployeeName();
  /**
   * <code>string employeeName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeNameBytes();

  /**
   * <code>string position = 3;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 3;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <code>int32 salary = 4;</code>
   */
  int getSalary();
}
