// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package grpc.employeeService;

/**
 * Protobuf type {@code employeeService.AddEmployeeRequest}
 */
public  final class AddEmployeeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employeeService.AddEmployeeRequest)
    AddEmployeeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddEmployeeRequest.newBuilder() to construct.
  private AddEmployeeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddEmployeeRequest() {
    employeeNumber_ = 0;
    employeeName_ = "";
    position_ = "";
    salary_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddEmployeeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            employeeNumber_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            employeeName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            position_ = s;
            break;
          }
          case 32: {

            salary_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.employeeService.EmployeeServiceImpl.internal_static_employeeService_AddEmployeeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.employeeService.EmployeeServiceImpl.internal_static_employeeService_AddEmployeeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.employeeService.AddEmployeeRequest.class, grpc.employeeService.AddEmployeeRequest.Builder.class);
  }

  public static final int EMPLOYEENUMBER_FIELD_NUMBER = 1;
  private int employeeNumber_;
  /**
   * <code>int32 employeeNumber = 1;</code>
   */
  public int getEmployeeNumber() {
    return employeeNumber_;
  }

  public static final int EMPLOYEENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object employeeName_;
  /**
   * <code>string employeeName = 2;</code>
   */
  public java.lang.String getEmployeeName() {
    java.lang.Object ref = employeeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employeeName_ = s;
      return s;
    }
  }
  /**
   * <code>string employeeName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEmployeeNameBytes() {
    java.lang.Object ref = employeeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employeeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private volatile java.lang.Object position_;
  /**
   * <code>string position = 3;</code>
   */
  public java.lang.String getPosition() {
    java.lang.Object ref = position_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      position_ = s;
      return s;
    }
  }
  /**
   * <code>string position = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPositionBytes() {
    java.lang.Object ref = position_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      position_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALARY_FIELD_NUMBER = 4;
  private int salary_;
  /**
   * <code>int32 salary = 4;</code>
   */
  public int getSalary() {
    return salary_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (employeeNumber_ != 0) {
      output.writeInt32(1, employeeNumber_);
    }
    if (!getEmployeeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, employeeName_);
    }
    if (!getPositionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, position_);
    }
    if (salary_ != 0) {
      output.writeInt32(4, salary_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (employeeNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, employeeNumber_);
    }
    if (!getEmployeeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, employeeName_);
    }
    if (!getPositionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, position_);
    }
    if (salary_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, salary_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.employeeService.AddEmployeeRequest)) {
      return super.equals(obj);
    }
    grpc.employeeService.AddEmployeeRequest other = (grpc.employeeService.AddEmployeeRequest) obj;

    boolean result = true;
    result = result && (getEmployeeNumber()
        == other.getEmployeeNumber());
    result = result && getEmployeeName()
        .equals(other.getEmployeeName());
    result = result && getPosition()
        .equals(other.getPosition());
    result = result && (getSalary()
        == other.getSalary());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPLOYEENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getEmployeeNumber();
    hash = (37 * hash) + EMPLOYEENAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmployeeName().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition().hashCode();
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + getSalary();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.employeeService.AddEmployeeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.employeeService.AddEmployeeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.employeeService.AddEmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.employeeService.AddEmployeeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employeeService.AddEmployeeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employeeService.AddEmployeeRequest)
      grpc.employeeService.AddEmployeeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.employeeService.EmployeeServiceImpl.internal_static_employeeService_AddEmployeeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.employeeService.EmployeeServiceImpl.internal_static_employeeService_AddEmployeeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.employeeService.AddEmployeeRequest.class, grpc.employeeService.AddEmployeeRequest.Builder.class);
    }

    // Construct using grpc.employeeService.AddEmployeeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employeeNumber_ = 0;

      employeeName_ = "";

      position_ = "";

      salary_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.employeeService.EmployeeServiceImpl.internal_static_employeeService_AddEmployeeRequest_descriptor;
    }

    @java.lang.Override
    public grpc.employeeService.AddEmployeeRequest getDefaultInstanceForType() {
      return grpc.employeeService.AddEmployeeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.employeeService.AddEmployeeRequest build() {
      grpc.employeeService.AddEmployeeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.employeeService.AddEmployeeRequest buildPartial() {
      grpc.employeeService.AddEmployeeRequest result = new grpc.employeeService.AddEmployeeRequest(this);
      result.employeeNumber_ = employeeNumber_;
      result.employeeName_ = employeeName_;
      result.position_ = position_;
      result.salary_ = salary_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.employeeService.AddEmployeeRequest) {
        return mergeFrom((grpc.employeeService.AddEmployeeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.employeeService.AddEmployeeRequest other) {
      if (other == grpc.employeeService.AddEmployeeRequest.getDefaultInstance()) return this;
      if (other.getEmployeeNumber() != 0) {
        setEmployeeNumber(other.getEmployeeNumber());
      }
      if (!other.getEmployeeName().isEmpty()) {
        employeeName_ = other.employeeName_;
        onChanged();
      }
      if (!other.getPosition().isEmpty()) {
        position_ = other.position_;
        onChanged();
      }
      if (other.getSalary() != 0) {
        setSalary(other.getSalary());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.employeeService.AddEmployeeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.employeeService.AddEmployeeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int employeeNumber_ ;
    /**
     * <code>int32 employeeNumber = 1;</code>
     */
    public int getEmployeeNumber() {
      return employeeNumber_;
    }
    /**
     * <code>int32 employeeNumber = 1;</code>
     */
    public Builder setEmployeeNumber(int value) {
      
      employeeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 employeeNumber = 1;</code>
     */
    public Builder clearEmployeeNumber() {
      
      employeeNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object employeeName_ = "";
    /**
     * <code>string employeeName = 2;</code>
     */
    public java.lang.String getEmployeeName() {
      java.lang.Object ref = employeeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employeeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employeeName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeNameBytes() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employeeName = 2;</code>
     */
    public Builder setEmployeeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employeeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employeeName = 2;</code>
     */
    public Builder clearEmployeeName() {
      
      employeeName_ = getDefaultInstance().getEmployeeName();
      onChanged();
      return this;
    }
    /**
     * <code>string employeeName = 2;</code>
     */
    public Builder setEmployeeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employeeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object position_ = "";
    /**
     * <code>string position = 3;</code>
     */
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string position = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string position = 3;</code>
     */
    public Builder setPosition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string position = 3;</code>
     */
    public Builder clearPosition() {
      
      position_ = getDefaultInstance().getPosition();
      onChanged();
      return this;
    }
    /**
     * <code>string position = 3;</code>
     */
    public Builder setPositionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      position_ = value;
      onChanged();
      return this;
    }

    private int salary_ ;
    /**
     * <code>int32 salary = 4;</code>
     */
    public int getSalary() {
      return salary_;
    }
    /**
     * <code>int32 salary = 4;</code>
     */
    public Builder setSalary(int value) {
      
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 salary = 4;</code>
     */
    public Builder clearSalary() {
      
      salary_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employeeService.AddEmployeeRequest)
  }

  // @@protoc_insertion_point(class_scope:employeeService.AddEmployeeRequest)
  private static final grpc.employeeService.AddEmployeeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.employeeService.AddEmployeeRequest();
  }

  public static grpc.employeeService.AddEmployeeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddEmployeeRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddEmployeeRequest>() {
    @java.lang.Override
    public AddEmployeeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddEmployeeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddEmployeeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddEmployeeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.employeeService.AddEmployeeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

