// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package grpc.employeeService;

public interface GetAllEmployeesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeService.GetAllEmployeesRequest)
    com.google.protobuf.MessageOrBuilder {
}
