// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package grpc.employeeService;

public interface GetEmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeService.GetEmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeDetails = 1;</code>
   */
  java.lang.String getEmployeeDetails();
  /**
   * <code>string employeeDetails = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeDetailsBytes();
}
