// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package grpc.employeeService;

public interface GetEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employeeService.GetEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 employeeNumber = 1;</code>
   */
  int getEmployeeNumber();
}
