// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockService.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>float price = 3;</code>
   */
  float getPrice();

  /**
   * <code>int32 qty = 4;</code>
   */
  int getQty();
}
