// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public interface StockLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockService.StockLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();
}
