// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public final class StockServiceImpl {
  private StockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_UpdateQtyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_UpdateQtyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_UpdateQtyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_UpdateQtyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_AddProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_AddProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_AddProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_AddProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stock.proto\022\014stockService\"4\n\020UpdateQty" +
      "Request\022\023\n\013stockNumber\030\001 \001(\005\022\013\n\003qty\030\002 \001(" +
      "\021\"5\n\021UpdateQtyResponse\022\017\n\007success\030\001 \001(\010\022" +
      "\017\n\007message\030\002 \001(\t\"%\n\016ProductRequest\022\023\n\013st" +
      "ockNumber\030\001 \001(\005\"W\n\017ProductResponse\022\023\n\013st" +
      "ockNumber\030\001 \001(\005\022\023\n\013description\030\002 \001(\t\022\r\n\005" +
      "price\030\003 \001(\002\022\013\n\003qty\030\004 \001(\005\"Y\n\021AddProductRe" +
      "quest\022\023\n\013stockNumber\030\001 \001(\005\022\023\n\013descriptio" +
      "n\030\002 \001(\t\022\r\n\005price\030\003 \001(\002\022\013\n\003qty\030\004 \001(\005\"6\n\022A" +
      "ddProductResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t2\204\002\n\014StockService\022R\n\tupdateQt" +
      "y\022\036.stockService.UpdateQtyRequest\032\037.stoc" +
      "kService.UpdateQtyResponse\"\000(\0010\001\022M\n\ngetP" +
      "roduct\022\034.stockService.ProductRequest\032\035.s" +
      "tockService.ProductResponse\"\0000\001\022Q\n\naddPr" +
      "oduct\022\037.stockService.AddProductRequest\032 " +
      ".stockService.AddProductResponse\"\000B\'\n\021gr" +
      "pc.stockServiceB\020StockServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stockService_UpdateQtyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stockService_UpdateQtyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_UpdateQtyRequest_descriptor,
        new java.lang.String[] { "StockNumber", "Qty", });
    internal_static_stockService_UpdateQtyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stockService_UpdateQtyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_UpdateQtyResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_stockService_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stockService_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_ProductRequest_descriptor,
        new java.lang.String[] { "StockNumber", });
    internal_static_stockService_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stockService_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_ProductResponse_descriptor,
        new java.lang.String[] { "StockNumber", "Description", "Price", "Qty", });
    internal_static_stockService_AddProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_stockService_AddProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_AddProductRequest_descriptor,
        new java.lang.String[] { "StockNumber", "Description", "Price", "Qty", });
    internal_static_stockService_AddProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_stockService_AddProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_AddProductResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
