// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public final class StockServiceImpl {
  private StockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_UpdateProductStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_UpdateProductStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_UpdateProductStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_UpdateProductStockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_StockLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_StockLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stockService_StockLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stockService_StockLevelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stock.proto\022\014stockService\"=\n\031UpdatePro" +
      "ductStockRequest\022\023\n\013stockNumber\030\001 \001(\005\022\013\n" +
      "\003qty\030\002 \001(\021\"-\n\032UpdateProductStockResponse" +
      "\022\017\n\007success\030\001 \001(\010\"(\n\021StockLevelRequest\022\023" +
      "\n\013stockNumber\030\001 \001(\005\"&\n\022StockLevelRespons" +
      "e\022\020\n\010quantity\030\001 \001(\0052\274\002\n\014StockService\022i\n\022" +
      "updateProductStock\022\'.stockService.Update" +
      "ProductStockRequest\032(.stockService.Updat" +
      "eProductStockResponse\"\000\022T\n\rgetStockLevel" +
      "\022\037.stockService.StockLevelRequest\032 .stoc" +
      "kService.StockLevelResponse\"\000\022k\n\020updateS" +
      "tockLevel\022\'.stockService.UpdateProductSt" +
      "ockRequest\032(.stockService.UpdateProductS" +
      "tockResponse\"\000(\0010\001B\'\n\021grpc.stockServiceB" +
      "\020StockServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stockService_UpdateProductStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stockService_UpdateProductStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_UpdateProductStockRequest_descriptor,
        new java.lang.String[] { "StockNumber", "Qty", });
    internal_static_stockService_UpdateProductStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stockService_UpdateProductStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_UpdateProductStockResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_stockService_StockLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stockService_StockLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_StockLevelRequest_descriptor,
        new java.lang.String[] { "StockNumber", });
    internal_static_stockService_StockLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stockService_StockLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stockService_StockLevelResponse_descriptor,
        new java.lang.String[] { "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
