// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public interface StockLevelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockService.StockLevelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity = 1;</code>
   */
  int getQuantity();
}
