// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package grpc.stockService;

public interface UpdateProductStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stockService.UpdateProductStockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
