// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface CancelOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.CancelOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNumber = 1;</code>
   */
  int getOrderNumber();
}
