// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface CancelOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.CancelOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
