// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface GetAllOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.GetAllOrdersRequest)
    com.google.protobuf.MessageOrBuilder {
}
