// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface GetOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.GetOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderDetails = 1;</code>
   */
  java.lang.String getOrderDetails();
  /**
   * <code>string orderDetails = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderDetailsBytes();
}
