// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public final class OrderServiceImpl {
  private OrderServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_PlaceOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_PlaceOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_CancelOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_CancelOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_CancelOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_CancelOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_GetOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_GetOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_GetOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_GetOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_TotalSalesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_TotalSalesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_TotalSalesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_TotalSalesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\014orderService\"y\n\021PlaceOrde" +
      "rRequest\022\023\n\013stockNumber\030\001 \001(\005\022\027\n\017prodDes" +
      "cription\030\002 \001(\t\022\021\n\tprodPrice\030\003 \001(\002\022\017\n\007pro" +
      "dQty\030\004 \001(\005\022\022\n\norderedQty\030\005 \001(\005\")\n\022Cancel" +
      "OrderRequest\022\023\n\013orderNumber\030\001 \001(\005\"&\n\023Can" +
      "celOrderResponse\022\017\n\007success\030\001 \001(\010\"&\n\017Get" +
      "OrderRequest\022\023\n\013orderNumber\030\001 \001(\005\"(\n\020Get" +
      "OrderResponse\022\024\n\014orderDetails\030\001 \001(\t\"\023\n\021T" +
      "otalSalesRequest\"(\n\022TotalSalesResponse\022\022" +
      "\n\nsalesTotal\030\001 \001(\0022\343\002\n\014OrderService\022Q\n\np" +
      "laceOrder\022\037.orderService.PlaceOrderReque" +
      "st\032\036.orderService.GetOrderResponse\"\000(\001\022T" +
      "\n\013cancelOrder\022 .orderService.CancelOrder" +
      "Request\032!.orderService.CancelOrderRespon" +
      "se\"\000\022T\n\017getOrderDetails\022\035.orderService.G" +
      "etOrderRequest\032\036.orderService.GetOrderRe" +
      "sponse\"\0000\001\022T\n\rgetTotalSales\022\037.orderServi" +
      "ce.TotalSalesRequest\032 .orderService.Tota" +
      "lSalesResponse\"\000B\'\n\021grpc.orderServiceB\020O" +
      "rderServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_orderService_PlaceOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orderService_PlaceOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_PlaceOrderRequest_descriptor,
        new java.lang.String[] { "StockNumber", "ProdDescription", "ProdPrice", "ProdQty", "OrderedQty", });
    internal_static_orderService_CancelOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orderService_CancelOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_CancelOrderRequest_descriptor,
        new java.lang.String[] { "OrderNumber", });
    internal_static_orderService_CancelOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_orderService_CancelOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_CancelOrderResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_orderService_GetOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_orderService_GetOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_GetOrderRequest_descriptor,
        new java.lang.String[] { "OrderNumber", });
    internal_static_orderService_GetOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_orderService_GetOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_GetOrderResponse_descriptor,
        new java.lang.String[] { "OrderDetails", });
    internal_static_orderService_TotalSalesRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_orderService_TotalSalesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_TotalSalesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_orderService_TotalSalesResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_orderService_TotalSalesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_TotalSalesResponse_descriptor,
        new java.lang.String[] { "SalesTotal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
