// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public final class OrderServiceImpl {
  private OrderServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_PlaceOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_PlaceOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_PlaceOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_PlaceOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_CancelOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_CancelOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_CancelOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_CancelOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_GetOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_GetOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_GetOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_GetOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_TotalSalesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_TotalSalesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_TotalSalesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_TotalSalesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderService_GetAllOrdersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderService_GetAllOrdersRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\014orderService\":\n\021PlaceOrde" +
      "rRequest\022\023\n\013stockNumber\030\001 \001(\005\022\020\n\010quantit" +
      "y\030\002 \001(\005\")\n\022PlaceOrderResponse\022\023\n\013orderNu" +
      "mber\030\001 \001(\021\")\n\022CancelOrderRequest\022\023\n\013orde" +
      "rNumber\030\001 \001(\005\"&\n\023CancelOrderResponse\022\017\n\007" +
      "success\030\001 \001(\010\"&\n\017GetOrderRequest\022\023\n\013ored" +
      "rNumber\030\001 \001(\005\"(\n\020GetOrderResponse\022\024\n\014ord" +
      "erDetails\030\001 \001(\t\"\023\n\021TotalSalesRequest\"(\n\022" +
      "TotalSalesResponse\022\022\n\nsalesTotal\030\001 \001(\002\"\025" +
      "\n\023GetAllOrdersRequest2\272\003\n\014OrderService\022S" +
      "\n\nplaceOrder\022\037.orderService.PlaceOrderRe" +
      "quest\032 .orderService.PlaceOrderResponse\"" +
      "\000(\001\022T\n\013cancelOrder\022 .orderService.Cancel" +
      "OrderRequest\032!.orderService.CancelOrderR" +
      "esponse\"\000\022R\n\017getOrderDetails\022\035.orderServ" +
      "ice.GetOrderRequest\032\036.orderService.GetOr" +
      "derResponse\"\000\022T\n\rgetTotalSales\022\037.orderSe" +
      "rvice.TotalSalesRequest\032 .orderService.T" +
      "otalSalesResponse\"\000\022U\n\014getAllOrders\022!.or" +
      "derService.GetAllOrdersRequest\032\036.orderSe" +
      "rvice.GetOrderResponse\"\0000\001B\'\n\021grpc.order" +
      "ServiceB\020OrderServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_orderService_PlaceOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orderService_PlaceOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_PlaceOrderRequest_descriptor,
        new java.lang.String[] { "StockNumber", "Quantity", });
    internal_static_orderService_PlaceOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orderService_PlaceOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_PlaceOrderResponse_descriptor,
        new java.lang.String[] { "OrderNumber", });
    internal_static_orderService_CancelOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_orderService_CancelOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_CancelOrderRequest_descriptor,
        new java.lang.String[] { "OrderNumber", });
    internal_static_orderService_CancelOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_orderService_CancelOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_CancelOrderResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_orderService_GetOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_orderService_GetOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_GetOrderRequest_descriptor,
        new java.lang.String[] { "OredrNumber", });
    internal_static_orderService_GetOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_orderService_GetOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_GetOrderResponse_descriptor,
        new java.lang.String[] { "OrderDetails", });
    internal_static_orderService_TotalSalesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_orderService_TotalSalesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_TotalSalesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_orderService_TotalSalesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_orderService_TotalSalesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_TotalSalesResponse_descriptor,
        new java.lang.String[] { "SalesTotal", });
    internal_static_orderService_GetAllOrdersRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_orderService_GetAllOrdersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderService_GetAllOrdersRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
