// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface PlaceOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.PlaceOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 orderNumber = 1;</code>
   */
  int getOrderNumber();
}
