// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface PlaceOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.PlaceOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();

  /**
   * <code>string prodDescription = 2;</code>
   */
  java.lang.String getProdDescription();
  /**
   * <code>string prodDescription = 2;</code>
   */
  com.google.protobuf.ByteString
      getProdDescriptionBytes();

  /**
   * <code>float prodPrice = 3;</code>
   */
  float getProdPrice();

  /**
   * <code>int32 prodQty = 4;</code>
   */
  int getProdQty();

  /**
   * <code>int32 orderedQty = 5;</code>
   */
  int getOrderedQty();
}
