// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface PlaceOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.PlaceOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
