// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface TotalSalesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.TotalSalesRequest)
    com.google.protobuf.MessageOrBuilder {
}
