// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package grpc.orderService;

public interface TotalSalesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderService.TotalSalesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float salesTotal = 1;</code>
   */
  float getSalesTotal();
}
